package Duppont;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * @author Raúl García Cortés
 * @e-mail GarciaCortes.Raul@gmail.com
 * @version 2014.06.22
 */
public class Principal extends javax.swing.JFrame {

    Animacion miBalon;
    private int Score;
    Menu menu;
    ColorFondo Fondo;

    public Principal() {
        initComponents();
        setTitle("Duppont Tester V2.0");
        this.setIconImage(new ImageIcon(getClass().getResource("/duppont/Bola.png")).getImage());
        setLocationRelativeTo(null); // Centrar ventana
        setResizable(false); // No maximizar ventana
        //se crea instancia a Animacion de animacion y se añade a la Principal
        Fondo = new ColorFondo();
        menu = new Menu();
        this.add(menu);
        this.add(Fondo);
        addKeyListener(new KeyListener() {

            @Override
            public void keyPressed(KeyEvent e) {
                int key = e.getKeyCode();

                switch (key) {
                    case KeyEvent.VK_ENTER:
                        System.out.println("Enter");
                        Game.removeAll(); // Limpiar pantalla
                        miBalon = new Animacion(Game.getSize(), Score); // Se crea la Instancia
                        Game.add(miBalon); // Se añade al Panel
                        miBalon.animar(true); // Inicia la animación
                        statusBar.setText("¡Buena Suerte!   |   Score: " + Score);
                        break;

                    case KeyEvent.VK_F1:
                        System.out.println("F1");
                        JOptionPane.showMessageDialog(null,
                                "CONTROL DEL JUEGO:"
                                + "\n Enter: Iniciar"
                                + "\n Mover mouse izquierda: Se moverá la barra a la izquierda"
                                + "\n Mover mouse derecha: Se moverá la barra a la derecha"
                                + "\n F1: Ayuda rápida"
                                + "\n Escape: Salir", "AYUDA", JOptionPane.QUESTION_MESSAGE);
                        statusBar.setText("AYUDA RÁPIDA");
                        break;

                }
            }

            @Override
            public void keyTyped(KeyEvent e) {
                System.out.println("keyTyped");
            }

            @Override
            public void keyReleased(KeyEvent e) {
                System.out.println("keyReleased");
            }
        });
    }

    public void salir(){
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Game = new javax.swing.JPanel();
        statusBar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        Game.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Game.setPreferredSize(new java.awt.Dimension(780, 460));

        javax.swing.GroupLayout GameLayout = new javax.swing.GroupLayout(Game);
        Game.setLayout(GameLayout);
        GameLayout.setHorizontalGroup(
            GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        GameLayout.setVerticalGroup(
            GameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        statusBar.setForeground(new java.awt.Color(255, 255, 255));
        statusBar.setText("¡Bienvenido! >:3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusBar, javax.swing.GroupLayout.DEFAULT_SIZE, 1001, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Game, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Game, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar)
                .addContainerGap())
        );

        statusBar.getAccessibleContext().setAccessibleName("StatusBar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
                new Sonido();
            }
        });
        /*try {
            Sonido s = new Sonido("Snow_Drift.wav");
            s.reproducir();
        } catch (Exception ex) {
            System.out.println("ERROR: No encontrado.");
        }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Game;
    private javax.swing.JLabel statusBar;
    // End of variables declaration//GEN-END:variables

}
